services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli --raw incr ping"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 5s
  celery:
    build: ..
    container_name: celery
    restart: unless-stopped
    env_file:
      - ./.env
    entrypoint: [ "celery", "-A", "server.tasks", "worker", "--loglevel=INFO" ]
    depends_on:
      redis:
        condition: service_healthy
  flask:
    build: ..
    container_name: flask
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - 5000:5000
    depends_on:
      redis:
        condition: service_healthy
      celery:
        condition: service_started
